In [1]:
x = rand(5)

5-element Array{Float64,1}:
 0.846315631290959
 0.5568361625963876
 0.23554511233396358
 0.4647657110632182
 0.8633887638198385

In [2]:
length(x)

5

In [3]:
using DelimitedFiles

In [4]:
A = readdlm("D:/julia-workspace/wdbc.txt", ',', Float64, '\n')

569×32 Array{Float64,2}:
 842302.0        0.0  17.99   10.38  …  0.7119  0.2654   0.4601  0.1189
 842517.0        0.0  20.57   17.77     0.2416  0.186    0.275   0.08902
      8.43009e7  0.0  19.69   21.25     0.4504  0.243    0.3613  0.08758
      8.43483e7  0.0  11.42   20.38     0.6869  0.2575   0.6638  0.173
      8.43584e7  0.0  20.29   14.34     0.4     0.1625   0.2364  0.07678
 843786.0        0.0  12.45   15.7   …  0.5355  0.1741   0.3985  0.1244
 844359.0        0.0  18.25   19.98     0.3784  0.1932   0.3063  0.08368
      8.44582e7  0.0  13.71   20.83     0.2678  0.1556   0.3196  0.1151
 844981.0        0.0  13.0    21.82     0.539   0.206    0.4378  0.1072
      8.4501e7   0.0  12.46   24.04     1.105   0.221    0.4366  0.2075
 845636.0        0.0  16.02   23.24  …  0.1459  0.09975  0.2948  0.08452
      8.461e7    0.0  15.78   17.89     0.3965  0.181    0.3792  0.1048
 846226.0        0.0  19.17   24.8      0.3639  0.1767   0.3176  0.1023
      ⋮                            

In [5]:
y = A[:,2] .+1

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [6]:
X = A[:,3:12]

569×10 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.3001   0.1471   0.2419  0.07871
 20.57   17.77  132.9   1326.0  0.08474     0.0869   0.07017  0.1812  0.05667
 19.69   21.25  130.0   1203.0  0.1096      0.1974   0.1279   0.2069  0.05999
 11.42   20.38   77.58   386.1  0.1425      0.2414   0.1052   0.2597  0.09744
 20.29   14.34  135.1   1297.0  0.1003      0.198    0.1043   0.1809  0.05883
 12.45   15.7    82.57   477.1  0.1278   …  0.1578   0.08089  0.2087  0.07613
 18.25   19.98  119.6   1040.0  0.09463     0.1127   0.074    0.1794  0.05742
 13.71   20.83   90.2    577.9  0.1189      0.09366  0.05985  0.2196  0.07451
 13.0    21.82   87.5    519.8  0.1273      0.1859   0.09353  0.235   0.07389
 12.46   24.04   83.97   475.9  0.1186      0.2273   0.08543  0.203   0.08243
 16.02   23.24  102.7    797.8  0.08206  …  0.03299  0.03323  0.1528  0.05697
 15.78   17.89  103.6    781.0  0.0971      0.09954  0.06606  0.1842  0.06082
 19.17   24.8   132.4   1123.0  0.0974 

In [7]:
size(X)

(569, 10)

In [8]:
X_all = A[:,3:end]

569×30 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.7119  0.2654   0.4601  0.1189
 20.57   17.77  132.9   1326.0  0.08474     0.2416  0.186    0.275   0.08902
 19.69   21.25  130.0   1203.0  0.1096      0.4504  0.243    0.3613  0.08758
 11.42   20.38   77.58   386.1  0.1425      0.6869  0.2575   0.6638  0.173
 20.29   14.34  135.1   1297.0  0.1003      0.4     0.1625   0.2364  0.07678
 12.45   15.7    82.57   477.1  0.1278   …  0.5355  0.1741   0.3985  0.1244
 18.25   19.98  119.6   1040.0  0.09463     0.3784  0.1932   0.3063  0.08368
 13.71   20.83   90.2    577.9  0.1189      0.2678  0.1556   0.3196  0.1151
 13.0    21.82   87.5    519.8  0.1273      0.539   0.206    0.4378  0.1072
 12.46   24.04   83.97   475.9  0.1186      1.105   0.221    0.4366  0.2075
 16.02   23.24  102.7    797.8  0.08206  …  0.1459  0.09975  0.2948  0.08452
 15.78   17.89  103.6    781.0  0.0971      0.3965  0.181    0.3792  0.1048
 19.17   24.8   132.4   1123.0  0.0974      0.3639  0.1767 

In [9]:
θ = zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [10]:
N, D = size(X)

(569, 10)

In [11]:
K = 2

2

In [12]:
μ = zeros(K,D)
σ = zeros(K,D)

2×10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [13]:
sum(y .==2)

357

In [14]:
θ[1] = sum(y .==1)/N
θ[2] = sum(y .==2)/N

0.6274165202108963

In [15]:
X_1 = X[y .==1, :]
X_2 = X[y .==2, :]

357×10 Array{Float64,2}:
 13.54   14.36  87.46  566.3  0.09779  …  0.06664   0.04781   0.1885  0.05766
 13.08   15.71  85.63  520.0  0.1075      0.04568   0.0311    0.1967  0.06811
  9.504  12.44  60.34  273.9  0.1024      0.02956   0.02076   0.1815  0.06905
 13.03   18.42  82.61  523.8  0.08983     0.02562   0.02923   0.1467  0.05863
  8.196  16.84  51.71  201.9  0.086       0.01588   0.005917  0.1769  0.06503
 12.05   14.63  78.04  449.3  0.1031   …  0.06592   0.02749   0.1675  0.06043
 13.49   22.3   86.91  561.0  0.08752     0.04751   0.03384   0.1809  0.05718
 11.76   21.6   74.72  427.9  0.08637     0.01657   0.01115   0.1495  0.05888
 13.64   16.34  87.21  571.8  0.07685     0.01857   0.01723   0.1353  0.05953
 11.94   18.24  75.71  437.6  0.08261     0.01972   0.01349   0.1868  0.0611
 11.52   18.75  73.34  409.0  0.09524  …  0.03036   0.02278   0.192   0.05907
 13.05   19.31  82.61  527.2  0.0806      0.000692  0.004167  0.1819  0.05501
  8.618  11.79  54.34  224.5  0.09752   

In [16]:
using Statistics
# giá trị trung bình một thuộc tính trong X_1(y = 1)
μ[1,:] = mean(X_1, dims = 1)
# giá trị trung bình một thuộc tính trong X_2(y = 2)
μ[2,:] = mean(X_2, dims = 1)
μ

2×10 Array{Float64,2}:
 17.4628  21.6049  115.365   978.376  …  0.08799    0.192909  0.0626801
 12.1465  17.9148   78.0754  462.79      0.0257174  0.174186  0.0628674

In [17]:
σ[1,:] = std(X_1,dims = 1)
σ[2,:] = std(X_2,dims = 1)
σ

2×10 Array{Float64,2}:
 3.20397  3.77947  21.8547  367.938  …  0.0343739  0.0276381  0.00757332
 1.78051  3.99512  11.8074  134.287     0.0159088  0.0248068  0.00674734

In [18]:
(θ,μ,σ)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.19290896226415097 0.06268009433962264; 12.146523809523813 17.914761904761903 … 0.17418599439775911 0.0628673949579832], [3.203971100779367 3.779469920776341 … 0.027638092143030174 0.007573315024808589; 1.7805116461410393 3.995124593675911 … 0.02480675820679328 0.0067473428139250636])

In [19]:
function train(X,y)
    N, D = size(X)
    K = length(unique(y))
    θ = zeros(K)
    μ = zeros(K,D)
    σ = zeros(K,D)
    for k =1:K
        θ[k] = sum(y .== k)/N
        X_k = X[y.==k,:]
        μ[k,:] = mean(X_k, dims = 1)
        σ[k,:] = std(X_k,dims = 1)
    end
    (θ,μ,σ)
end

train (generic function with 1 method)

In [20]:
X

569×10 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.3001   0.1471   0.2419  0.07871
 20.57   17.77  132.9   1326.0  0.08474     0.0869   0.07017  0.1812  0.05667
 19.69   21.25  130.0   1203.0  0.1096      0.1974   0.1279   0.2069  0.05999
 11.42   20.38   77.58   386.1  0.1425      0.2414   0.1052   0.2597  0.09744
 20.29   14.34  135.1   1297.0  0.1003      0.198    0.1043   0.1809  0.05883
 12.45   15.7    82.57   477.1  0.1278   …  0.1578   0.08089  0.2087  0.07613
 18.25   19.98  119.6   1040.0  0.09463     0.1127   0.074    0.1794  0.05742
 13.71   20.83   90.2    577.9  0.1189      0.09366  0.05985  0.2196  0.07451
 13.0    21.82   87.5    519.8  0.1273      0.1859   0.09353  0.235   0.07389
 12.46   24.04   83.97   475.9  0.1186      0.2273   0.08543  0.203   0.08243
 16.02   23.24  102.7    797.8  0.08206  …  0.03299  0.03323  0.1528  0.05697
 15.78   17.89  103.6    781.0  0.0971      0.09954  0.06606  0.1842  0.06082
 19.17   24.8   132.4   1123.0  0.0974 

In [21]:
y

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [22]:
(θ, μ, σ) = train(X,y)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.19290896226415097 0.06268009433962264; 12.146523809523813 17.914761904761903 … 0.17418599439775911 0.0628673949579832], [3.203971100779367 3.779469920776341 … 0.027638092143030174 0.007573315024808589; 1.7805116461410393 3.995124593675911 … 0.02480675820679328 0.0067473428139250636])

In [23]:
X[100, :]

10-element Array{Float64,1}:
  14.42
  19.77
  94.48
 642.5
   0.09752
   0.1141
   0.09388
   0.05839
   0.1879
   0.0639

In [24]:
y[100]

1.0

In [25]:
X[400, :]

10-element Array{Float64,1}:
  11.8
  17.26
  75.26
 431.9
   0.09087
   0.06232
   0.02853
   0.01638
   0.1847
   0.06019

In [26]:
y[400]

2.0

In [27]:
xNew = X[100,:]

10-element Array{Float64,1}:
  14.42
  19.77
  94.48
 642.5
   0.09752
   0.1141
   0.09388
   0.05839
   0.1879
   0.0639

In [28]:
#Compute posterior probability: P(y = 1|xNew), P(y=2|xNew)
# log P(y = 1|xNew) = log(prior_1) + log(likelihood_1) = α_1 - Β_1
α_1 = log(θ[1])
u = (xNew - μ[1,:]) ./σ[1,:]
β_1 = sum(log.(σ[1,:])) + (u'*u)/2
# log P(y = 2|xNew) = log(prior_2) + log(likelihood_2) = α_2 - Β_2
α_2 = log(θ[2])
v = (xNew - μ[2,:]) ./σ[2,:]
β_2 = sum(log.(σ[2,:])) + (v'*v)/2

-8.098419462134306

In [29]:
α_1 - β_1

6.754347357346591

In [30]:
α_2 - β_2

7.632274809787614

In [31]:
u = rand(5)

5-element Array{Float64,1}:
 0.7321631849533274
 0.060689508419605964
 0.6825213646107657
 0.30085049039982814
 0.644760101003087

In [32]:
argmax(u)

1

In [33]:
θ

2-element Array{Float64,1}:
 0.37258347978910367
 0.6274165202108963

In [34]:
function classify(xNew, θ, μ, σ)
    K = length(θ)
    scores = zeros(K)
    for k =1:K
        α_k = log(θ[k])
        u = (xNew - μ[k, :])./σ[k, :]
        β_k = sum(log.(σ[k, :])) + sum(u.*u)/2
        scores[k] = α_k - β_k
    end
    return argmax(scores)
end

classify (generic function with 1 method)

In [35]:
xNew = X[100, :]
yNew = classify(xNew, θ,μ,σ)

2

In [36]:
ŷ = zeros(N)
for i = 1:N
    ŷ[i] = classify(X[i,:],θ,μ,σ)
end

In [37]:
ŷ

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [38]:
accuracy = sum(y .== ŷ)/N

0.9138840070298769

In [39]:
function evaluate(X, y, θ, μ, σ)
    N = length(y)
    ŷ = zeros(N)
    for i =1:N 
        ŷ[i] = classify(X[i,:],θ,μ,σ)
    end
    sum(y .== ŷ)/N
end

evaluate (generic function with 1 method)

In [40]:
evaluate(X[1:100,:],y[1:100],θ,μ,σ)

0.83

In [41]:
evaluate(X[N-100:end,:],y[N-100:end],θ,μ,σ)

0.9306930693069307

In [42]:
evaluate(X,y,θ,μ,σ)

0.9138840070298769

In [43]:
a = zeros(2,2)
b = zeros(2,2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

In [44]:
a[1,1] = 1
a[1,2] = 2
a[2,1] = 3
a[2,2] = 5
a

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  5.0

In [45]:
b[1,:] = std(a, dims = 1)

1×2 Array{Float64,2}:
 1.41421  2.12132

In [46]:
π

π = 3.1415926535897...