In [1]:
X = zeros(3,3)
N,D = size(X)
function checkCol(X,Sum_)
    sumCol_X=sum(X,dims=1)
    checkSum=sum(sumCol_X .== Sum_)
    if(checkSum == 3) 
        return true
    else
        return false
    end
end

checkCol (generic function with 1 method)

In [2]:
function checkRow(X,Sum_)
    sumRow_X=sum(X,dims=2)
    checkSum=sum(sumRow_X .== Sum_)
    if(checkSum == 3) 
        return true
    else
        return false
    end
end

checkRow (generic function with 1 method)

In [3]:
function checkCross(X,Sum_)
    checkSum = sum( [[sum(i->X[i,i],1:3)] [sum(i->X[N+1-i,i],1:3)]] .== Sum_)
    if(checkSum == 2)
        return true
    else
        return false
    end
end

checkCross (generic function with 1 method)

In [6]:
function fillNumber(X,Sum_,i,j)
    for k = 0:9
        if(i==3 && j==3)
            X[i,j]=k
            if(checkCol(X,Sum_) && checkCross(X,Sum_) && checkRow(X,Sum_))
                show(stdout, "text/plain", convert(Array{Int64,2}, X))
                println()
                return X
            end        
        elseif(j==3)
            X[i,j]=k
            fillNumber(X,Sum_,i+1,1)
        else
            X[i,j]=k
            fillNumber(X,Sum_,i,j+1)
        end
    end
end

fillNumber (generic function with 1 method)

In [7]:
fillNumber(X,15,1,1)

3×3 Array{Int64,2}:
 1  9  5
 9  5  1
 5  1  9
3×3 Array{Int64,2}:
 2  7  6
 9  5  1
 4  3  8
3×3 Array{Int64,2}:
 2  8  5
 8  5  2
 5  2  8
3×3 Array{Int64,2}:
 2  9  4
 7  5  3
 6  1  8
3×3 Array{Int64,2}:
 3  5  7
 9  5  1
 3  5  7
3×3 Array{Int64,2}:
 3  6  6
 8  5  2
 4  4  7
3×3 Array{Int64,2}:
 3  7  5
 7  5  3
 5  3  7
3×3 Array{Int64,2}:
 3  8  4
 6  5  4
 6  2  7
3×3 Array{Int64,2}:
 3  9  3
 5  5  5
 7  1  7
3×3 Array{Int64,2}:
 4  3  8
 9  5  1
 2  7  6
3×3 Array{Int64,2}:
 4  4  7
 8  5  2
 3  6  6
3×3 Array{Int64,2}:
 4  5  6
 7  5  3
 4  5  6
3×3 Array{Int64,2}:
 4  6  5
 6  5  4
 5  4  6
3×3 Array{Int64,2}:
 4  7  4
 5  5  5
 6  3  6
3×3 Array{Int64,2}:
 4  8  3
 4  5  6
 7  2  6
3×3 Array{Int64,2}:
 4  9  2
 3  5  7
 8  1  6
3×3 Array{Int64,2}:
 5  1  9
 9  5  1
 1  9  5
3×3 Array{Int64,2}:
 5  2  8
 8  5  2
 2  8  5
3×3 Array{Int64,2}:
 5  3  7
 7  5  3
 3  7  5
3×3 Array{Int64,2}:
 5  4  6
 6  5  4
 4  6  5
3×3 Array{Int64,2}:
 5  5  5
 5  5  5
 5  5  5
3×3 Array{Int

In [7]:
fillNumber(X,10,1,1)

In [13]:
X

3×3 Array{Float64,2}:
 9.0  9.0  9.0
 9.0  9.0  9.0
 9.0  9.0  9.0