In [3]:
using DelimitedFiles

In [4]:
A = readdlm("D:/julia-workspace/Fuel Consumption Dataset.txt", ',', '\n')

52×8 Array{Any,2}:
 "State"          "Drivers"  …       "MPC"          "Pop"    "Tax"
 "AL"      3559897              12737        3451586       18
 "AK"       472211               7639.16      457728        8
 "AZ"      3550367               9411.55     3907526       18
 "AR"      1961883              11268.4      2072622       21.7
 "CA"     21623793           …   8923.89    25599275       18
 "CO"      3287922               9722.73     3322455       22
 "CT"      2650374               9021.35     2651452       25
 "DE"       564099              10891.3       610269       23
 "DC"       328094               6555.94      468575       20
 "FL"     12743403           …   9531.23    12741821       13.6
 "GA"      5833802              13248.6      6250708        7.5
 "HI"       787820               7108.75      949184       16
 ⋮                           ⋱      ⋮                      
 "RI"       660435           …   7625         827474       29
 "SC"      2849885              11469.6   

In [5]:
B = A[2:end,2:end]

51×7 Array{Any,2}:
  3559897   2382507  23471   94440  12737      3451586  18
   472211    235400  30064   13628   7639.16    457728   8
  3550367   2428430  25578   55245   9411.55   3907526  18
  1961883   1358174  22257   98132  11268.4    2072622  21.7
 21623793  14691753  32275  168771   8923.89  25599275  18
  3287922   2048664  32949   85854   9722.73   3322455  22
  2650374   1458279  40640   20910   9021.35   2651452  25
   564099    382043  31255    5814  10891.3     610269  23
   328094    148769  37383    1534   6555.94    468575  20
 12743403   7471117  28145  117299   9531.23  12741821  13.6
  5833802   4693703  27940  115534  13248.6    6250708   7.5
   787820    404684  28221    4278   7108.75    949184  16
   896666    609051  24180   46310  10879.4     969166  25
        ⋮                                            ⋮  
   660435    399113  29685    6053   7625       827474  29
  2849885   2217141  24321   66167  11469.6    3115130  16
   544997    402472  26115   8356

In [6]:
Drivers = B[:,1]
FuelC = B[:,2]
Income = B[:,3]
Miles = B[:,4]
MPC = B[:,5]
Pop = B[:,6]
Tax = B[:,7]

51-element Array{Any,1}:
 18
  8
 18
 21.7
 18
 22
 25
 23
 20
 13.6
  7.5
 16
 25
  ⋮
 29
 16
 22
 20
 20
 24.5
 20
 17.5
 23
 25.65
 27.3
 14

In [7]:
y = FuelC .*1000 ./Pop

51-element Array{Float64,1}:
 690.2644175749931
 514.2792225950783
 621.475071439064
 655.2926679346258
 573.9128549539
 616.6115116683296
 549.9926078239395
 626.0239337079222
 317.492397161607
 586.3460960564428
 750.9074172077787
 426.3493695637516
 628.4279473279088
   ⋮
 482.3269371605634
 711.7330576894062
 697.0527770609517
 638.2310609545192
 681.100136591545
 591.4999458878183
 691.0227118608703
 681.0311214380635
 576.0697495580029
 562.4109333021843
 581.7937169457123
 842.7917524261421

In [8]:
Dlic = Drivers .* 1000 ./Pop

51-element Array{Float64,1}:
 1031.3800670184662
 1031.6410619407159
  908.5971532882954
  946.5705758213509
  844.7033363249545
  989.6061797676718
  999.5934303166717
  924.3448380959871
  700.1952729018834
 1000.124158077562
  933.3025954819838
  829.9971343806891
  925.1934137185993
    ⋮
  798.1338386462897
  914.8526706750602
  943.8959041619977
  942.0443649520342
  835.2955548937877
  935.7885458586665
 1075.288201725559
  889.9195143953199
  930.8562455424127
  904.8936009399672
  882.3290812294349
  970.7527456125191

In [9]:
log_Miles = log2.(Miles)

51-element Array{Float64,1}:
 16.527110421116006
 13.734286232096347
 15.753556277508256
 16.58243604314262
 17.364707500812983
 16.389597731548893
 14.351905441476942
 12.505315356136236
 10.583082767502933
 16.839831188560346
 16.81795795303127
 12.062720767165045
 15.499036136591055
  ⋮
 12.563434635710198
 16.013824249050675
 16.35052487195447
 16.422360477832594
 18.198286758380327
 15.365228849251544
 13.802819250816214
 16.109851054234124
 16.305367097057776
 15.175120670274953
 16.781654267845337
 14.736190500960927

In [10]:
X = [ones(length(y)) Tax Dlic Income log_Miles]

51×5 Array{Any,2}:
 1.0  18     1031.38   23471  16.5271
 1.0   8     1031.64   30064  13.7343
 1.0  18      908.597  25578  15.7536
 1.0  21.7    946.571  22257  16.5824
 1.0  18      844.703  32275  17.3647
 1.0  22      989.606  32949  16.3896
 1.0  25      999.593  40640  14.3519
 1.0  23      924.345  31255  12.5053
 1.0  20      700.195  37383  10.5831
 1.0  13.6   1000.12   28145  16.8398
 1.0   7.5    933.303  27940  16.818
 1.0  16      829.997  28221  12.0627
 1.0  25      925.193  24180  15.499
 ⋮                            
 1.0  29      798.134  29685  12.5634
 1.0  16      914.853  24321  16.0138
 1.0  22      943.896  26115  16.3505
 1.0  20      942.044  26239  16.4224
 1.0  20      835.296  27871  18.1983
 1.0  24.5    935.789  23907  15.3652
 1.0  20     1075.29   26901  13.8028
 1.0  17.5    889.92   31162  16.1099
 1.0  23      930.856  31528  16.3054
 1.0  25.65   904.894  21915  15.1751
 1.0  27.3    882.329  28232  16.7817
 1.0  14      970.753  27230  14.7362

In [11]:
size(X)

(51, 5)

In [12]:
size(y)

(51,)

In [13]:
θ = convert(Array{Float64}, (X'*X))^(-1)*X'*y

5-element Array{Any,1}:
 154.1928445772677
  -4.227983208329644
   0.47187121344200195
  -0.006135330970417315
  18.545274506047924

In [14]:
using Statistics
std(Income, dims=1)

1-element Array{Float64,1}:
 4451.637223561245

In [15]:
a = [3,4,6]

3-element Array{Int64,1}:
 3
 4
 6

In [38]:
((std(Tax)^2+mean(Tax)^2)/51)/2


4.1850460641080724

In [34]:
mean(Tax)

20.15490196078431