In [1]:
using DelimitedFiles

In [49]:
A = readdlm("D:/julia-workspace/iris-train.txt", '\t', Float64, '\n')

130×5 Array{Float64,2}:
 1.0  5.1  3.5  1.4  0.2
 1.0  4.7  3.2  1.3  0.2
 1.0  4.6  3.1  1.5  0.2
 1.0  5.0  3.6  1.4  0.2
 1.0  4.6  3.4  1.4  0.3
 1.0  4.4  2.9  1.4  0.2
 1.0  4.9  3.1  1.5  0.1
 1.0  5.4  3.7  1.5  0.2
 1.0  4.8  3.4  1.6  0.2
 1.0  4.8  3.0  1.4  0.1
 1.0  4.3  3.0  1.1  0.1
 1.0  5.8  4.0  1.2  0.2
 1.0  5.7  4.4  1.5  0.4
 ⋮                   
 3.0  6.1  2.6  5.6  1.4
 3.0  6.3  3.4  5.6  2.4
 3.0  6.0  3.0  4.8  1.8
 3.0  6.9  3.1  5.4  2.1
 3.0  6.7  3.1  5.6  2.4
 3.0  6.9  3.1  5.1  2.3
 3.0  5.8  2.7  5.1  1.9
 3.0  6.7  3.3  5.7  2.5
 3.0  6.3  2.5  5.0  1.9
 3.0  6.5  3.0  5.2  2.0
 3.0  6.2  3.4  5.4  2.3
 3.0  5.9  3.0  5.1  1.8

In [50]:
y = A[:,1]

130-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0

In [51]:
X = A[:,2:end]

130×4 Array{Float64,2}:
 5.1  3.5  1.4  0.2
 4.7  3.2  1.3  0.2
 4.6  3.1  1.5  0.2
 5.0  3.6  1.4  0.2
 4.6  3.4  1.4  0.3
 4.4  2.9  1.4  0.2
 4.9  3.1  1.5  0.1
 5.4  3.7  1.5  0.2
 4.8  3.4  1.6  0.2
 4.8  3.0  1.4  0.1
 4.3  3.0  1.1  0.1
 5.8  4.0  1.2  0.2
 5.7  4.4  1.5  0.4
 ⋮              
 6.1  2.6  5.6  1.4
 6.3  3.4  5.6  2.4
 6.0  3.0  4.8  1.8
 6.9  3.1  5.4  2.1
 6.7  3.1  5.6  2.4
 6.9  3.1  5.1  2.3
 5.8  2.7  5.1  1.9
 6.7  3.3  5.7  2.5
 6.3  2.5  5.0  1.9
 6.5  3.0  5.2  2.0
 6.2  3.4  5.4  2.3
 5.9  3.0  5.1  1.8

In [52]:
size(X)

(130, 4)

In [53]:
θ = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [54]:
N, D = size(X)

(130, 4)

In [55]:
K = 3

3

In [56]:
μ = zeros(K,D)
σ = zeros(K,D)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [57]:
θ[1] = sum(y .==1)/N
θ[2] = sum(y .==2)/N
θ[3] = sum(y .==3)/N
θ

3-element Array{Float64,1}:
 0.33076923076923076
 0.3384615384615385
 0.33076923076923076

In [58]:
X_1 = X[y .==1, :]
X_2 = X[y .==2, :]
X_3 = X[y .==3, :]

43×4 Array{Float64,2}:
 6.3  3.3  6.0  2.5
 5.8  2.7  5.1  1.9
 7.1  3.0  5.9  2.1
 6.3  2.9  5.6  1.8
 6.5  3.0  5.8  2.2
 7.6  3.0  6.6  2.1
 4.9  2.5  4.5  1.7
 6.7  2.5  5.8  1.8
 7.2  3.6  6.1  2.5
 6.5  3.2  5.1  2.0
 6.4  2.7  5.3  1.9
 6.8  3.0  5.5  2.1
 5.8  2.8  5.1  2.4
 ⋮              
 6.1  2.6  5.6  1.4
 6.3  3.4  5.6  2.4
 6.0  3.0  4.8  1.8
 6.9  3.1  5.4  2.1
 6.7  3.1  5.6  2.4
 6.9  3.1  5.1  2.3
 5.8  2.7  5.1  1.9
 6.7  3.3  5.7  2.5
 6.3  2.5  5.0  1.9
 6.5  3.0  5.2  2.0
 6.2  3.4  5.4  2.3
 5.9  3.0  5.1  1.8

In [59]:
using Statistics
# giá trị trung bình một thuộc tính trong X_1(y = 1)
μ[1,:] = mean(X_1, dims = 1)
# giá trị trung bình một thuộc tính trong X_2(y = 2)
μ[2,:] = mean(X_2, dims = 1)
μ[3,:] = mean(X_3, dims = 1)
μ

3×4 Array{Float64,2}:
 5.01395  3.40233  1.46279  0.24186
 5.90227  2.75909  4.22955  1.31364
 6.56047  2.96977  5.53256  2.01628

In [60]:
σ[1,:] = std(X_1,dims = 1)
σ[2,:] = std(X_2,dims = 1)
σ[3,:] = std(X_3,dims = 1)
σ

3×4 Array{Float64,2}:
 0.354952  0.390048  0.152789  0.109615
 0.520505  0.311275  0.483485  0.204133
 0.638875  0.33419   0.566409  0.282784

In [61]:
function train(X,y)
    N, D = size(X)
    K = length(unique(y))
    θ = zeros(K)
    μ = zeros(K,D)
    σ = zeros(K,D)
    for k =1:K
        θ[k] = sum(y .== k)/N
        X_k = X[y.==k,:]
        μ[k,:] = mean(X_k, dims = 1)
        σ[k,:] = std(X_k,dims = 1)
    end
    (θ,μ,σ)
end

train (generic function with 1 method)

In [62]:
(θ, μ, σ) = train(X,y)

([0.33076923076923076, 0.3384615384615385, 0.33076923076923076], [5.013953488372093 3.40232558139535 1.4627906976744185 0.24186046511627904; 5.902272727272727 2.759090909090909 4.229545454545454 1.3136363636363635; 6.560465116279069 2.9697674418604647 5.532558139534883 2.016279069767442], [0.35495230756018964 0.39004784327604836 0.15278876768419214 0.109615253847122; 0.5205045121282594 0.3112750834709582 0.4834851891406739 0.20413277609154645; 0.6388753268658623 0.33419048155557596 0.5664092959926881 0.28278397657688786])

In [63]:
function classify(xNew, θ, μ, σ)
    K = length(θ)
    scores = zeros(K)
    for k =1:K
        α_k = log(θ[k])
        u = (xNew - μ[k, :])./σ[k, :]
        β_k = sum(log.(σ[k, :])) + sum(u.*u)/2
        scores[k] = α_k - β_k
    end
    return argmax(scores)
end

classify (generic function with 1 method)

In [64]:
ŷ = zeros(N)
for i = 1:N
    ŷ[i] = classify(X[i,:],θ,μ,σ)
end

In [65]:
ŷ

130-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0

In [66]:
accuracy = sum(y .== ŷ)/N

0.9538461538461539

In [67]:
function evaluate(X, y, θ, μ, σ)
    N = length(y)
    ŷ = zeros(N)
    for i =1:N 
        ŷ[i] = classify(X[i,:],θ,μ,σ)
    end
    sum(y .== ŷ)/N
end

evaluate (generic function with 1 method)

In [68]:
evaluate(X[1:100,:],y[1:100],θ,μ,σ)

0.96