In [1]:
using DelimitedFiles

In [2]:
A = readdlm("D:/julia-workspace/wdbc.txt", ',', Float64, '\n')

569×32 Array{Float64,2}:
 842302.0        0.0  17.99   10.38  …  0.7119  0.2654   0.4601  0.1189
 842517.0        0.0  20.57   17.77     0.2416  0.186    0.275   0.08902
      8.43009e7  0.0  19.69   21.25     0.4504  0.243    0.3613  0.08758
      8.43483e7  0.0  11.42   20.38     0.6869  0.2575   0.6638  0.173
      8.43584e7  0.0  20.29   14.34     0.4     0.1625   0.2364  0.07678
 843786.0        0.0  12.45   15.7   …  0.5355  0.1741   0.3985  0.1244
 844359.0        0.0  18.25   19.98     0.3784  0.1932   0.3063  0.08368
      8.44582e7  0.0  13.71   20.83     0.2678  0.1556   0.3196  0.1151
 844981.0        0.0  13.0    21.82     0.539   0.206    0.4378  0.1072
      8.4501e7   0.0  12.46   24.04     1.105   0.221    0.4366  0.2075
 845636.0        0.0  16.02   23.24  …  0.1459  0.09975  0.2948  0.08452
      8.461e7    0.0  15.78   17.89     0.3965  0.181    0.3792  0.1048
 846226.0        0.0  19.17   24.8      0.3639  0.1767   0.3176  0.1023
      ⋮                            

In [3]:
y = A[:,2].+1

569-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 2.0
 2.0
 2.0
 2.0
 2.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0

In [4]:
X = [ones(length(y)) A[:,3:31]]

569×30 Array{Float64,2}:
 1.0  17.99   10.38  122.8   1001.0  …  0.6656   0.7119  0.2654   0.4601
 1.0  20.57   17.77  132.9   1326.0     0.1866   0.2416  0.186    0.275
 1.0  19.69   21.25  130.0   1203.0     0.4245   0.4504  0.243    0.3613
 1.0  11.42   20.38   77.58   386.1     0.8663   0.6869  0.2575   0.6638
 1.0  20.29   14.34  135.1   1297.0     0.205    0.4     0.1625   0.2364
 1.0  12.45   15.7    82.57   477.1  …  0.5249   0.5355  0.1741   0.3985
 1.0  18.25   19.98  119.6   1040.0     0.2576   0.3784  0.1932   0.3063
 1.0  13.71   20.83   90.2    577.9     0.3682   0.2678  0.1556   0.3196
 1.0  13.0    21.82   87.5    519.8     0.5401   0.539   0.206    0.4378
 1.0  12.46   24.04   83.97   475.9     1.058    1.105   0.221    0.4366
 1.0  16.02   23.24  102.7    797.8  …  0.1551   0.1459  0.09975  0.2948
 1.0  15.78   17.89  103.6    781.0     0.5609   0.3965  0.181    0.3792
 1.0  19.17   24.8   132.4   1123.0     0.3903   0.3639  0.1767   0.3176
 ⋮                         

In [5]:
(N,D) = size(X)
θ = zeros(D)

30-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [6]:
function loss(X::Array{Float64,2}, y::Array{Float64}, θ::Array{Float64})::Float64
    N = length(y)
    h = sigmoid.(X*θ)
    l = y'*log.(h)+(1 .- y)'*log.(1 .- h)
    J = -l/N + 0.
    J
end

loss (generic function with 1 method)

In [7]:
function sigmoid(z)
    h = 1/(1+exp(-z))
end

sigmoid (generic function with 1 method)

In [8]:
function gradient(X, y, θ)::Array{Float64}
    N = length(y)
    h = sigmoid.(X*θ)
    X'*(h - y)/N .+ 0.

end

gradient (generic function with 1 method)

In [9]:
function bgd(X, y, θ_0, α = 0.001, T = 100)::Array{Array{Float64}}
    θ = θ_0
    θs = []
    for t=1:T
        ∇ = gradient(X, y, θ)
        θ = θ - α * ∇
        push!(θs, θ) # Day tung phan tu θ vao duoi
    end
    θs
end

bgd (generic function with 3 methods)

In [10]:
θ_0 = zeros(D)
α = 0.01
T = 1000
θs = bgd(X, y, θ_0, α, T)

1000-element Array{Array{Float64,N} where N,1}:
 [0.011274165202108964, 0.14684575571177505, 0.2088484182776801, 0.9497031634446397, 6.178067662565906, 0.0010620214411247804, 0.0010241690685413006, 0.0007329697021089631, 0.00040595098418277686, 0.001998681019332162  …  4.1787705623901586e-5, 0.1652930316344464, 0.2759235500878735, 1.0821956942003512, 7.909543057996485, 0.0014458594903339187, 0.002417442970123023, 0.00240394535149385, 0.00104010723198594, 0.0031459455184534267]
 [0.017548330404217927, 0.22305505272407733, 0.3212485940246046, 1.4395611599297011, 9.081689806678384, 0.0016422414762741655, 0.001526633216168717, 0.0010219428251318102, 0.0005673062390158173, 0.003091552724077329  …  6.460089191564148e-5, 0.24924011423550085, 0.4234609841827769, 1.62808532513181, 11.416170474516697, 0.002229876010544815, 0.0035635607205623905, 0.0034469482864674878, 0.0015071833479789105, 0.004841513181019332]
 [0.02382249560632689, 0.2992643497363796, 0.43364876977152905, 1.9294191564147627, 

In [11]:
Js = map(θ -> loss(X, y, θ), θs)
θs[end,end]

30-element Array{Float64,1}:
    6.2791652021090005
   76.27993347100188
  112.49662398945709
  490.31784165201725
 2906.8965896308955
    0.5807018365553617
    0.5029858525483184
    0.28941711960193045
    0.16159985056239304
    1.0937775140597386
    0.3947544098418224
    1.784405473637942
    7.662950699472686
    ⋮
    0.06190752198594112
    0.12924891536028205
    0.022832160811072033
   84.02842855008919
  147.66582021089587
  546.4259369947354
 3511.030332161635
    0.7846783631810044
    1.1473890756590472
    1.0443638773901451
    0.4676491471089551
    1.6970180404217812

In [46]:
U=sort(X*θs[50])
U[1:10]
# I=X*θs[50]
indexin(U[1:10],I)

10-element Array{Union{Nothing, Int64},1}:
 102
 540
 539
  47
 569
 152
 315
 176
  62
 526

In [12]:
function classify(X, θ)
    h = X'*θ
    if (h<0) 1.0 else 2.0 end
end

classify (generic function with 1 method)

In [85]:
prediction = map(i->classify(X[i,:], θs[end,end]), 1:N)
accuracy = sum(y .== prediction)/N

0.6274165202108963

In [86]:
loss(X,y,θ)

0.6931471805599444

In [87]:
using Optim

In [88]:
function cost(θ::Array{Float64})::Float64
    N = length(y)
    h = sigmoid.(X*θ)
    l = y'*log.(h)+(1 .- y)'*log.(1 .- h)
    J = -l/N + 0.
    J
end

cost (generic function with 1 method)

In [90]:
result = optimize(cost ,θ_0,LBFGS())

 * Status: success

 * Candidate solution
    Final objective value:     -3.450840e+00

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 1.08e-19 ≰ 0.0e+00
    |x - x'|/|x'|          = 1.86e-17 ≰ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 3.53e+02 ≰ 1.0e-08

 * Work counters
    Seconds run:   1  (vs limit Inf)
    Iterations:    3
    f(x) calls:    250
    ∇f(x) calls:   250


In [91]:
θ_best=Optim.minimizer(result)

30-element Array{Float64,1}:
 8.318685596852164e-6
 0.00010835069834944169
 0.0001540995983156637
 0.0007007420846799021
 0.004558510679754554
 7.836165521894495e-7
 7.55687035615193e-7
 5.408244771026467e-7
 2.995324747706633e-7
 1.4747343780790587e-6
 5.227166371501709e-7
 2.809924263934073e-6
 1.013894757084528e-5
 ⋮
 8.91543036435192e-8
 1.7107708247520888e-7
 3.083321720515636e-8
 0.00012196209092375149
 0.0002035912389714674
 0.0007985022015035035
 0.005836086373790123
 1.066832914316519e-6
 1.7837194732105112e-6
 1.7737602039784095e-6
 7.674470698791803e-7
 2.321247844352625e-6

In [92]:
Optim.minimum(result)

-3.4508402313526867

In [93]:
prediction = map(i->classify(X[i,:], θ_best), 1:N)
accuracy = sum(y .== prediction)/N

0.6274165202108963