In [2]:
using Flux
using DelimitedFiles
using Plots
using CUDA

In [3]:
using Flux:gradient

In [4]:
f(x) = 3x^2 + 2x +1

f (generic function with 1 method)

In [8]:
md"""
    ### LaTex
    this is a function: $f(x) = 3x^2 + 2x +1$ in LaTex format.
"""

LoadError: LoadError: UndefVarError: @md_str not defined
in expression starting at In[8]:1

In [9]:
f(5)

86

In [10]:
df(x) = gradient(f,x)

df (generic function with 1 method)

In [15]:
df(5)[1]

32

In [37]:
my_sin(x) = sum([(-1)^k * x^(1+2k)/factorial(1+2k) for k = 0:6])

my_sin (generic function with 1 method)

In [38]:
x = 0.5

0.5

In [39]:
my_sin(x)

0.479425538604203

In [40]:
sin(x)

0.479425538604203

In [41]:
gradient(my_sin,x)[1]

0.8775825618903734

In [42]:
my_loss(W, b, x) = sum(W*x .+ b)

my_loss (generic function with 1 method)

In [43]:
W = rand(3,4)

3×4 Array{Float64,2}:
 0.463314  0.156237  0.70505   0.220666
 0.369133  0.875368  0.912097  0.42289
 0.314315  0.294375  0.65018   0.334582

In [44]:
b = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [45]:
x = rand(4)

4-element Array{Float64,1}:
 0.07366510250136549
 0.624648947027109
 0.5364497603485778
 0.5154195698809747

In [46]:
my_loss(W, b, x)

2.6332076196645993

In [50]:
grads = gradient(my_loss, W, b, x)

([0.07366510250136549 0.624648947027109 0.5364497603485778 0.5154195698809747; 0.07366510250136549 0.624648947027109 0.5364497603485778 0.5154195698809747; 0.07366510250136549 0.624648947027109 0.5364497603485778 0.5154195698809747], 3-element Fill{Float64}: entries equal to 1.0, [1.1467618682910299, 1.3259804919376499, 2.2673278715069722, 0.9781380203312791])

In [51]:
grads[2]

3-element Fill{Float64}: entries equal to 1.0